# Generated by Django 5.2.4 on 2025-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_item_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
